### ISSUE TITLE
slack channel for ansible is off

### ISSUE THREAD

**Issue by vvb** [CiscoUcs/ciscoucs.github.io#2]
https://ciscoucs.github.io/

UCS Ansible Slack Room points to http://tiny.cc/ucsm-slack

It should point to https://ucspython.herokuapp.com/ 

We use a common slack channel for all opensource support. Because ansible heavily depends on the python bindings provided by the SDKs.

**Comment by vallard** [comment]
Thanks.  That other link was for the unofficial UCS Python Ansible SDK.  We'll point it all to the same place now.  Let me know if you think we need additional links.
